#####################
# LAYOUT
#####################
default_nmaster=1
new_is_master=1
smartgaps=0

# Use scroller (niri-like) on all tags
tagrule=id:0,layout_name:scroller
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller

# Scroller feel
scroller_default_proportion=0.5
scroller_proportion_preset=0.33333,0.5,0.66667
scroller_prefer_overspread=1
scroller_focus_center=0
scroller_prefer_center=0
scroller_structs=10